name: "🐛 Bug Fix"
description: "버그 수정"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: 🐞 버그 설명
      description: 어떤 문제가 발생했는지 간략히 적어주세요.
      placeholder: 예) 로그인 시 500 오류 발생
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔄 재현 절차
      description: 버그를 확인할 수 있는 단계(step)를 순서대로 작성해주세요.
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🤔 예상 vs 실제 동작
      description: 정상 동작과 실제 동작을 비교해 적어주세요.
      placeholder: |
        - 예상: 로그인 성공 후 /home 이동
        - 실제: 500 Internal Server Error
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📸 스크린샷 또는 로그
      description: (선택) 오류 화면이나 콘솔 로그를 첨부해주세요.
    validations:
      required: false